config/routes.rb
Rails.application.routes.draw do

  resources :rems, except: :show
  resources :entries
  resources :parent_entries, path: 'trips' do
    resources :child_entries, path: 'entries'
  end
  resources :relationships
  resources :files, only: :create
  devise_for :users
  root to: 'home#index'

end

app/models/parent_entry.rb
# frozen_string_literal: true

class ParentEntry < Entry
  has_many :child_entries, foreign_key: :entry_id, dependent: :destroy

  validates_presence_of :end_date

  validate :start_and_end_date

  scope :relationship_parent_event_types, lambda { |relationship|
    where(relationship: relationship).order(event_type: :asc).pluck(:event_type).uniq
  }

  private

  def start_and_end_date
    return if end_date > start_date
    errors.add(:end_date, 'cannot be before the start date.')
  end
end

#     t.string "title"
#     t.text "description"
#     t.date "start_date"
#     t.date "end_date"
#     t.string "event_type"
#     t.string "type"
#     t.string "status"
#     t.bigint "user_id"
#     t.bigint "relationship_id"
#     t.bigint "entry_id"
#     t.datetime "created_at", precision: 6, null: false
#     t.datetime "updated_at", precision: 6, null: false
#     t.index ["entry_id"], name: "index_entries_on_entry_id"
#     t.index ["relationship_id"], name: "index_entries_on_relationship_id"
#     t.index ["user_id"], name: "index_entries_on_user_id"

app/controllers/parent_entries_controller.rb
class ParentEntriesController < ApplicationController
  before_action :set_parent_entry, only: %i[show edit update destroy]

  # GET /entries or /entries.json
  def index
    @parent_entries = current_user.parent_entries.order(start_date: :desc)
  end

  # GET /entries/1 or /entries/1.json
  def show
    @child_entries = @parent_entry.child_entries.with_attached_images.order(start_date: :asc)
  end

  # GET /entries/new
  def new
    @parent_entry = ParentEntry.new
  end

  # GET /entries/1/edit
  def edit
    set_media_files
  end

  # POST /entries or /entries.json
  def create
    @parent_entry = ParentEntry.new(parent_entry_params)

    respond_to do |format|
      if @parent_entry.save
        format.html { redirect_to @parent_entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @parent_entry }
      else
        set_media_files
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @parent_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @parent_entry.update(parent_entry_params)
        format.html { redirect_to @parent_entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @parent_entry }
      else
        set_media_files
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @parent_entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @parent_entry.destroy
    respond_to do |format|
      format.html { redirect_to parent_entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_parent_entry
    @parent_entry = ParentEntry.find(params[:id])
  end

  def set_media_files
    @media_files_json = json_mock_files(@parent_entry.images)
  end

  # Only allow a list of trusted parameters through.
  def parent_entry_params
    params.require(:parent_entry).permit(
      :title,
      :description,
      :start_date,
      :end_date,
      :event_type,
      :status,
      :content,
      :main_image,
      images: []
    ).merge(user: current_user, relationship: current_relationship)
  end
end

app/views/parent_entries/_form.html.haml
#parent-entry-form{ 'data-controller': 'dropzone', 'data-dropzone-max-file-size': '100', 'data-dropzone-max-files': 100,
  'data-dropzone-accepted-files': 'image/jpg, image/jpeg, image/gif, image/png, video/mp4', 'data-dropzone-delete-url': '/files',
  'data-dropzone-record-name': 'parent-entry', 'data-dropzone-existing-files': @media_files_json}
  = simple_form_for @parent_entry do |f|
    = f.input :title
    = f.input :description

    = f.input :start_date, as: :flatpickr, placeholder: 'Start Date',
     input_html: { data: { controller: "flatpickr", flatpickr_date_format: "%B %d %Y", flatpickr_alt_input: true,
    flatpickr_alt_format: "%B %d %Y", flatpickr_default_date: f.object.start_date.present? ? f.object.start_date.strftime("%B %d %Y") : Time.current }}

    = f.input :end_date, as: :flatpickr, placeholder: 'Start Date',
    input_html: {data: { controller: "flatpickr", flatpickr_date_format: "%B %d %Y", flatpickr_alt_input: true,
    flatpickr_alt_format: "%B %d %Y", flatpickr_default_date: f.object.end_date.present? ? f.object.end_date.strftime("%B %d %Y") : Time.current.tomorrow }}

    .form-floating.mb-3{'data-controller': 'select2'}
      = f.select :event_type, ParentEntry.relationship_parent_event_types(current_user.relationship),
        {include_blank: false, required: true, include_hidden: false}, class: 'form-select select2'
      = f.label :event_type

    .mb-3= f.rich_text_area :content, class: 'form-control'


    = f.input :main_image, as: :file, input_html: {multiple: false}

    = render partial: "shared/dropzone_component", locals: {f: f, column_name: 'images', file_size: '3'}


    .d-flex.justify-content-between
      = link_to 'Back', parent_entries_path,  class: 'btn btn-secondary'
      = f.button :submit, class: "btn-primary"

app/views/parent_entries/edit.html.haml
%h1 Editing entry

= render 'form'

app/views/parent_entries/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h1 Trips
  .btn.btn-primary= link_to 'New Event', new_parent_entry_path

- @parent_entries.each do |entry|
  .card.mb-3
    .card-body
      .d-flex.justify-content-between.align-items-center
        .card-title.m-0
          %h5= entry.title
        .dropdown.pointer
          .bi.bi-three-dots{'data-bs-toggle': "dropdown" }
          %ul.dropdown-menu
            %li
              = link_to entry, class: 'dropdown-item' do
                Show
            %li
              = link_to edit_parent_entry_path(entry), class: 'dropdown-item' do
                Edit
            %li
              = link_to entry, method: :delete, class: 'dropdown-item', data: { confirm: 'Are you sure?' } do
                Destroy

      .card-subtitle.text-muted
        = entry.start_date.strftime("%B %d, %Y")
        \-
        = entry.end_date.strftime("%B %d, %Y")

      %p.card-text.text-muted
        = simple_format entry.description

%br

app/views/parent_entries/new.html.haml
%h1 New Trip

= render 'form'

app/views/parent_entries/show.html.haml
%p#notice= notice
#entry-show.mb-3
  .card
    .card-body
      .d-flex.justify-content-between.align-items-center
        .card-title.d-flex.justify-content-start.align-items-baseline
          %h4= @parent_entry.title
          .card-subtitle.text-muted.ps-2
            = @parent_entry.start_date.strftime("%B %d, %Y")
            \-
            = @parent_entry.end_date.strftime("%B %d, %Y")
        .dropdown.pointer
          .bi.bi-three-dots{'data-bs-toggle': "dropdown" }
          %ul.dropdown-menu
            %li
              = link_to edit_parent_entry_path(@parent_entry), class: 'dropdown-item' do
                Edit
            %li
              = link_to @parent_entry, method: :delete, class: 'dropdown-item', data: { confirm: 'Are you sure?' } do
                Destroy

      .row
        .col-12.col-sm-6
          .card-text.text-muted
            = @parent_entry.description

      .row.my-3
        .col
          .entry-content.card-text
            = @parent_entry.content

-# - if @parent_entry.main_image.attached?
-#   = image_tag @parent_entry.main_image.representation(resize_to_limit: [100, 100])

= render partial: "shared/media_gallery", locals: {resource: @parent_entry}

.row.mt-5
  .col
    .d-flex.justify-content-between
      .trip-entries-lists-title
        %h3
          Trip Entries
          %span
            %small.text-muted= @child_entries.count
      .add-entry-plus-icon
        = link_to 'Add Trip Entry', new_parent_entry_child_entry_path(@parent_entry), class: "btn btn-primary"


    .row
      .col-12.col-sm-8
        .ps-4
          .list-group.mt-2.mb-3
            - @child_entries.each do |child_entry|
              .mb-3
                = link_to parent_entry_child_entry_path(@parent_entry, child_entry), class: '' do
                  - if child_entry.main_image.attached?
                    .card.mb-3{style: "max-width: 1000px;"}
                      .row.g-0
                        .col-md-4
                          = image_tag child_entry.main_image.representation(resize_to_limit: [500, 500]), class: 'img-fluid rounded-start'
                          -#%img.img-fluid.rounded-start{alt: "...", src: "..."}/
                        .col-md-8
                          .card-body
                            %h5.card-title child_entry.title
                            %small= child_entry.start_date.strftime("%B %d, %Y")
                            %p.card-text= child_entry.description
                  - else
                    .list-group
                      .list-group-item
                        .d-flex.w-100.justify-content-between
                          %h5.mb-1= child_entry.title
                          %small= child_entry.start_date.strftime("%B %d, %Y")
                        %p.card-text= child_entry.description