config/routes.rb
Rails.application.routes.draw do

  resources :rems, except: :show
  resources :entries
  resources :parent_entries, path: 'trips' do
    resources :child_entries, path: 'entries'
  end
  resources :relationships
  resources :files, only: :create
  devise_for :users
  root to: 'home#index'

end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :relationship

  has_one_attached :main_image, dependent: :destroy
  has_many_attached :images, dependent: :destroy

  has_rich_text :content

  # Validations
  validates_presence_of :title, :description, :start_date, :event_type, :content

  scope :relationship_event_types, lambda { |relationship|
    where(relationship: relationship).where.not(type: 'ParentEntry').order(event_type: :asc).pluck(:event_type).uniq
  }

  def parent_entry?
    type == 'ParentEntry'
  end

  def mine?(current_user)
    current_user == user
  end

  def trip?
    event_type == 'Trip'
  end

end

#     t.string "title"
#     t.text "description"
#     t.date "start_date"
#     t.date "end_date"
#     t.string "event_type"
#     t.string "type"
#     t.string "status"
#     t.bigint "user_id"
#     t.bigint "relationship_id"
#     t.bigint "entry_id"
#     t.datetime "created_at", precision: 6, null: false
#     t.datetime "updated_at", precision: 6, null: false
#     t.index ["entry_id"], name: "index_entries_on_entry_id"
#     t.index ["relationship_id"], name: "index_entries_on_relationship_id"
#     t.index ["user_id"], name: "index_entries_on_user_id"

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = current_user.entries.where(type: nil).order(start_date: :desc)
  end

  # GET /entries/1 or /entries/1.json
  def show
    # @child_entries = @entry.child_entries.with_attached_images.order(start_date: :asc)
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
    set_media_files
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @entry, notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        set_media_files
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        set_media_files
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  def set_media_files
    @media_files_json = json_mock_files(@entry.images)
  end

  # Only allow a list of trusted parameters through.
  def entry_params
    params.require(:entry).permit(
      :title,
      :description,
      :start_date,
      :end_date,
      :event_type,
      :status,
      :content,
      :main_image,
      images: []
    ).merge(user: current_user, relationship: current_relationship)
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
#entry-form{ 'data-controller': 'dropzone', 'data-dropzone-max-file-size': '100', 'data-dropzone-max-files': 100,
  'data-dropzone-accepted-files': 'image/jpg, image/jpeg, image/gif, image/png, video/mp4', 'data-dropzone-delete-url': '/files',
  'data-dropzone-record-name': 'parent-entry', 'data-dropzone-existing-files': @media_files_json}
  = simple_form_for @entry, wrapper: :floating_labels_form, wrapper_mappings: {select: :floating_labels_select}  do |f|
    = f.input :title
    = f.input :description
    = f.input :start_date, as: :flatpickr, placeholder: 'Start Date', input_html: {data: { controller: "flatpickr", flatpickr_date_format: "%B %d %Y", flatpickr_alt_input: true,
      flatpickr_alt_format: "%B %d %Y", flatpickr_default_date: f.object.start_date.present? ? f.object.start_date.strftime("%B %d %Y") : Time.current }}


    .form-floating.mb-3{'data-controller': 'select2'}
      = f.select :event_type, Entry.relationship_event_types(current_user.relationship),
        {include_blank: false, required: true, include_hidden: false}, class: 'form-select select2'
      = f.label :event_type

    .mb-3= f.rich_text_area :content, class: 'form-control'


    = f.input :main_image, as: :file, input_html: {multiple: false}

    = render partial: "shared/dropzone_component", locals: {f: f, column_name: 'images', file_size: '3'}

    .d-flex.justify-content-between
      = link_to 'Back', entries_path,  class: 'btn btn-secondary'
      = f.button :submit, class: "btn-primary"

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

app/views/entries/index.html.haml
.d-flex.justify-content-between.align-items-center
  %h1 Entries
  .btn.btn-primary= link_to 'New Event', new_entry_path
- @entries.each do |entry|
  .card.mb-3
    .card-body
      .d-flex.justify-content-between.align-items-center
        .card-title.m-0
          %h5= entry.title
        .dropdown.pointer
          .bi.bi-three-dots{'data-bs-toggle': "dropdown" }
          %ul.dropdown-menu
            %li
              = link_to entry, class: 'dropdown-item' do
                Show
            %li
              = link_to edit_entry_path(entry), class: 'dropdown-item' do
                Edit
            %li
              = link_to entry, method: :delete, class: 'dropdown-item', data: { confirm: 'Are you sure?' } do
                Destroy

      .card-subtitle.text-muted
        = entry.start_date.strftime("%B %d, %Y")
      %p.card-text.text-muted
        = simple_format entry.description

app/views/entries/new.html.haml
%h1 New entry

= render 'form'

app/views/entries/show.html.haml
%p#notice= notice
#entry-show
  .card.mb-3
    .card-body
      .d-flex.justify-content-between.align-items-center
        .card-title.d-flex.justify-content-start.align-items-baseline
          %h4= @entry.title
          .card-subtitle.text-muted.ps-2
            = @entry.start_date.strftime("%B %d, %Y")
        .dropdown.pointer
          .bi.bi-three-dots{'data-bs-toggle': "dropdown" }
          %ul.dropdown-menu
            %li
              = link_to edit_entry_path(@entry), class: 'dropdown-item' do
                Edit
            %li
              = link_to @entry, method: :delete, class: 'dropdown-item', data: { confirm: 'Are you sure?' } do
                Destroy

      .row
        .col-12.col-sm-6
          .card-text.text-muted
            = @entry.description

      .row.my-3
        .col
          .entry-content.card-text
            = @entry.content


      -# - if @entry.main_image.attached?
      -#   = image_tag @entry.main_image.representation(resize_to_limit: [100, 100])

  = render partial: "shared/media_gallery", locals: {resource: @entry}



  .btn.btn-secondary= link_to 'Back', entries_path