config/routes.rb
Rails.application.routes.draw do

  resources :rems, except: :show
  resources :entries
  resources :parent_entries, path: 'trips' do
    resources :child_entries, path: 'entries'
  end
  resources :relationships
  resources :files, only: :create
  devise_for :users
  root to: 'home#index'

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  has_many :users
  has_many :entries
  has_many :parent_entries, class_name: 'ParentEntry'
  # has_many :rems
  # has_many :entry_rems, class_name: 'Rem', through: :entries


end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :set_relationship, only: %i[ show edit update destroy ]

  # GET /relationships or /relationships.json
  def index
    @relationship = current_relationship
    @entries = @relationship.entries.where(entry_id: nil).order(start_date: :desc)
    Preloader::RelationshipEntries.preload(@entries)
    # @entries = @entries.group("entries.start_date") #.group_by(&:start_date)
  end

  # GET /relationships/1 or /relationships/1.json
  def show
  end

  # GET /relationships/new
  def new
    @relationship = Relationship.new
  end

  # GET /relationships/1/edit
  def edit
  end

  # POST /relationships or /relationships.json
  def create
    @relationship = Relationship.new(relationship_params)

    respond_to do |format|
      if @relationship.save
        format.html { redirect_to @relationship, notice: "Relationship was successfully created." }
        format.json { render :show, status: :created, location: @relationship }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relationships/1 or /relationships/1.json
  def update
    respond_to do |format|
      if @relationship.update(relationship_params)
        format.html { redirect_to @relationship, notice: "Relationship was successfully updated." }
        format.json { render :show, status: :ok, location: @relationship }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @relationship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relationships/1 or /relationships/1.json
  def destroy
    @relationship.destroy
    respond_to do |format|
      format.html { redirect_to relationships_url, notice: "Relationship was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_relationship
    @relationship = Relationship.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def relationship_params
    params.require(:relationship).permit(:title, :description, :start_date, :type)
  end
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/views/relationships/_form.html.haml
= form_for @relationship do |f|
  - if @relationship.errors.any?
    #error_explanation
      %h2= "#{pluralize(@relationship.errors.count, "error")} prohibited this relationship from being saved:"
      %ul
        - @relationship.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :start_date
    = f.date_select :start_date
  .field
    = f.label :type
    = f.text_field :type
  .actions
    = f.submit 'Save'

app/views/relationships/_my_entry.haml
.row.entry.my-entry
  .col-12.d-flex.justify-content-start
    = link_to entry_path(entry) do
      .card.mb-3
        .card-body
          .d-flex.flex-wrap.justify-content-between.align-items-center
            .card-title
              %h5= entry.title
            .card-subtitle.mb-2.text-muted
              %h6= entry.start_date.strftime("%B %d, %Y")
          %p.card-text
            = entry.description

app/views/relationships/_parent_trip.haml
.row.entry.parent-trip
  .col-12.d-flex.justify-content-center
    = link_to parent_entry_path(entry) do
      .card.mb-3
        - if entry.main_image.attached?
          = image_tag entry.main_image.representation(resize_to_limit: [500, 500]), class: "img-fluid card-img-top card-image"
        - else
          = image_tag("trip_map.jpg", class: "img-fluid card-img-top card-image")
        .card-body
          .d-flex.flex-wrap.justify-content-between.align-items-center.mb-3
            .d-flex.flex-column
              .card-title.m-0
                %h5.m-0= entry.title
              .card-subtitle.text-muted
                %p
                  %small= pluralize(entry.child_entries.count, 'entry')
            .card-subtitle.mb-2.text-muted
              %h6= "#{entry.start_date.strftime('%B %d')} - #{entry.end_date.strftime('%B %d, %Y')}"
          %p.card-text
            = entry.description

app/views/relationships/_their_entry.haml
.row.entry.their-entry
  .col-12.d-flex.justify-content-end
    = link_to entry_path(entry) do
      .card.mb-3
        .card-body
          .d-flex.flex-wrap.justify-content-between.align-items-center
            .card-title
              %h5= entry.title
            .card-subtitle.mb-2.text-muted
              %h6= entry.start_date.strftime("%B %d, %Y")
          %p.card-text
            = entry.description

app/views/relationships/edit.html.haml
%h1 Editing relationship

= render 'form'

= link_to 'Show', @relationship
\|
= link_to 'Back', relationships_path

app/views/relationships/index.html.haml
#memory-lane
  - @entries.each do |entry|
    - if entry.parent_entry?
      = render partial: 'parent_trip', locals: {entry: entry}
    - elsif entry.mine?(current_user)
      = render partial: 'my_entry', locals: {entry: entry}
    -else
      = render partial: 'their_entry', locals: {entry: entry}


%br

app/views/relationships/new.html.haml
%h1 New relationship

= render 'form'

= link_to 'Back', relationships_path

app/views/relationships/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @relationship.title
%p
  %b Description:
  = @relationship.description
%p
  %b Start date:
  = @relationship.start_date
%p
  %b Type:
  = @relationship.type

= link_to 'Edit', edit_relationship_path(@relationship)
\|
= link_to 'Back', relationships_path