config/routes.rb
Rails.application.routes.draw do

  resources :rems, except: :show
  resources :entries
  resources :parent_entries, path: 'trips' do
    resources :child_entries, path: 'entries'
  end
  resources :relationships
  resources :files, only: :create
  devise_for :users
  root to: 'home#index'

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title UsStory
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
  %body
    -#%p.notice= notice
    -#%p.alert= alert
    - if user_signed_in?
      %nav.navbar.navbar-expand-lg.navbar-dark.bg-primary.mb-5
        .container-fluid
          %button.navbar-toggler(aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation" data-bs-target="#navbar" data-bs-toggle="collapse" type="button")
            %span.navbar-toggler-icon
          #navbar.collapse.navbar-collapse
            = link_to root_path do
              .navbar-brand
                %span.text-muted Us
                %span Story
            %ul.navbar-nav.me-auto.mb-2.mb-lg-0
              %li.nav-item
                = link_to relationships_path, class: 'nav-link' do
                  Memory Lane
              %li.nav-item
                = link_to entries_path, class: 'nav-link' do
                  Entries
              %li.nav-item
                = link_to parent_entries_path, class: 'nav-link' do
                  Trips
              %li.nav-item
                = link_to rems_path, class: 'nav-link' do
                  Rems

            .d-flex
              .nav-item
                = link_to destroy_user_session_path, method: :delete, class: 'nav-link' do
                  Log out


    .container
      = yield